fixed a problem Vivek found. This part of the code is getting uglier and uglier...
-----
Kohsuke,

I have WSDL parts for rpclit operation like this:

<message name="holderOperation">
    <part name="holder1" type="xsd:string"/>
    <part name="holder2" type="xsd:string"/>
</message>

A bridge is created with TypeReference, {""}holder1 and xml type 
"xsd:string". When Bridge.marshall() is called with null value jaxb 
throws this exception:

the object parameter to marshal() is not marshallable
java.lang.IllegalArgumentException: the object parameter to marshal() is 
not marshallable
        at 
com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:195)
        at 
com.sun.xml.bind.v2.runtime.BridgeImpl.marshal(BridgeImpl.java:44)

Brdige.marshall() for any non-null value works fine. Looks like this is 
a bug. Or are we doing something wrong?


-vivek.


-- Vivek Pandey Web Services Standards and Technologies Sun Microsystems Inc.