fixed the issue Jitsu reported. We really need to think about testing this better.
------------------------------------------

java.security.AccessControlException: access denied  
(java.lang.RuntimePermission accessDeclaredMembers)
         at java.security.AccessControlContext.checkPermission 
(AccessControlContext.java:264)
         at java.security.AccessController.checkPermission 
(AccessController.java:427)
         at java.lang.SecurityManager.checkPermission 
(SecurityManager.java:532)
         at java.lang.SecurityManager.checkMemberAccess 
(SecurityManager.java:1662)
         at java.lang.Class.checkMemberAccess(Class.java:2125)
         at java.lang.Class.getDeclaredConstructor(Class.java:1952)
         at com.sun.xml.bind.v2.ClassFactory.create0 
(ClassFactory.java:48)
         at  
com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.createInstance 
(ClassBeanInfoImpl.java:246)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInst 
ance(UnmarshallingContext.java:260)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.AbstractUnmarshallingEventHandl 
erImpl.spawnChild(AbstractUnmarshallingEventHandlerImpl.java:154)
         at com.sun.xml.bind.v2.runtime.property.Unmarshaller 
$SpawnChildHandler.handle(Unmarshaller.java:528)
         at com.sun.xml.bind.v2.runtime.property.Unmarshaller 
$EpsilonHandler.activate(Unmarshaller.java:74)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.pushConten 
tHandler(UnmarshallingContext.java:479)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElem 
ent(UnmarshallingContext.java:378)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startEleme 
nt(UnmarshallingContext.java:329)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElemen 
t(InterningXmlVisitor.java:30)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement 
(SAXConnector.java:99)
         at  
com.sun.xml.bind.v2.stax.XMLStreamReaderToContentHandler.handleStartElem 
ent(XMLStreamReaderToContentHandler.java:251)
         at  
com.sun.xml.bind.v2.stax.XMLStreamReaderToContentHandler.bridge 
(XMLStreamReaderToContentHandler.java:108)
         at  
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal 
(UnmarshallerImpl.java:252)
         at com.sun.xml.bind.v2.runtime.BridgeImpl.unmarshal 
(BridgeImpl.java:60)
         at  
com.sun.xml.ws.encoding.jaxb.JAXBTypeSerializer.deserialize 
(JAXBTypeSerializer.java:177)
         at com.sun.xml.ws.encoding.soap.SOAPDecoder.decodeBodyContent 
(SOAPDecoder.java:218)
         at com.sun.xml.ws.encoding.soap.SOAPDecoder.decodeBody 
(SOAPDecoder.java:192)
         at com.sun.xml.ws.encoding.soap.SOAPDecoder.decodeEnvelope 
(SOAPDecoder.java:125)
         at com.sun.xml.ws.client.SOAPXMLDecoder.toInternalMessage 
(SOAPXMLDecoder.java:172)
         at com.sun.xml.ws.client.SOAPMessageDispatcher.receive 
(SOAPMessageDispatcher.java:195)
         at com.sun.xml.ws.client.SOAPMessageDispatcher.doSend 
(SOAPMessageDispatcher.java:116)
         at com.sun.xml.ws.client.SOAPMessageDispatcher.send 
(SOAPMessageDispatcher.java:69)
         at com.sun.xml.ws.encoding.soap.internal.DelegateBase.send 
(DelegateBase.java:65)
         at  
com.sun.xml.ws.client.EndpointIFInvocationHandler.implementSEIMethod 
(EndpointIFInvocationHandler.java:122)
         at com.sun.xml.ws.client.EndpointIFInvocationHandler.invoke 
(EndpointIFInvocationHandler.java:76)
         at $Proxy19.sayHello(Unknown Source)
         at client.HelloClient.main(Unknown Source)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke 
(NativeMethodAccessorImpl.java:39)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke 
(DelegatingMethodAccessorImpl.java:25)
         at java.lang.reflect.Method.invoke(Method.java:585)
         at com.sun.enterprise.util.Utility.invokeApplicationMain 
(Utility.java:233)
         at com.sun.enterprise.appclient.Main.<init>(Main.java:437)
         at com.sun.enterprise.appclient.Main.main(Main.java:103)
java.lang.NullPointerException
         at  
com.sun.xml.ws.encoding.soap.ClientEncoderDecoder.toMessageInfo 
(ClientEncoderDecoder.java:54)
         at com.sun.xml.ws.client.SOAPXMLDecoder.toMessageInfo 
(SOAPXMLDecoder.java:138)
         at com.sun.xml.ws.client.SOAPMessageDispatcher.receive 
(SOAPMessageDispatcher.java:199)
         at com.sun.xml.ws.client.SOAPMessageDispatcher.doSend 
(SOAPMessageDispatcher.java:116)
         at com.sun.xml.ws.client.SOAPMessageDispatcher.send 
(SOAPMessageDispatcher.java:69)
         at com.sun.xml.ws.encoding.soap.internal.DelegateBase.send 
(DelegateBase.java:65)
         at  
com.sun.xml.ws.client.EndpointIFInvocationHandler.implementSEIMethod 
(EndpointIFInvocationHandler.java:122)
         at com.sun.xml.ws.client.EndpointIFInvocationHandler.invoke 
(EndpointIFInvocationHandler.java:76)
         at $Proxy19.sayHello(Unknown Source)
         at client.HelloClient.main(Unknown Source)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke 
(NativeMethodAccessorImpl.java:39)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke 
(DelegatingMethodAccessorImpl.java:25)
         at java.lang.reflect.Method.invoke(Method.java:585)
         at com.sun.enterprise.util.Utility.invokeApplicationMain 
(Utility.java:233)
         at com.sun.enterprise.appclient.Main.<init>(Main.java:437)
         at com.sun.enterprise.appclient.Main.main(Main.java:103)